[versions]
assertj = "3.24.2"
json-unit ="3.2.2"

junit-jupiter = "5.9.2"
junit-platform = "1.9.2"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
json-unit-assertj = { module = "net.javacrumbs.json-unit:json-unit-assertj", version.ref = "json-unit" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-jupiter" }

junit-platform-suite-api = { module = "org.junit.platform:junit-platform-suite-api", version.ref = "junit-platform" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[bundles]
assertj = ["assertj", "json-unit-assertj"]
junit-api = [ "junit-jupiter-api", "junit-platform-suite-api" ]
junit-runtime = [ "junit-jupiter-engine", "junit-vintage-engine", "junit-platform-suite", "junit-platform-launcher" ]
